# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Apr  3 01:54:06 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SweetPea(object):
    def setupUi(self, SweetPea):
        SweetPea.setObjectName("SweetPea")
        SweetPea.resize(770, 625)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/logo_ic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SweetPea.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(SweetPea)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.forward = QtGui.QPushButton(self.centralWidget)
        self.forward.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/fwd_ic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forward.setIcon(icon1)
        self.forward.setObjectName("forward")
        self.gridLayout.addWidget(self.forward, 0, 2, 1, 1)
        self.cancel = QtGui.QPushButton(self.centralWidget)
        self.cancel.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/cncl_ic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel.setIcon(icon2)
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 0, 3, 1, 1)
        self.webView = QtWebKit.QWebView(self.centralWidget)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.gridLayout.addWidget(self.webView, 1, 1, 1, 8)
        self.reload = QtGui.QPushButton(self.centralWidget)
        self.reload.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/rld_ic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reload.setIcon(icon3)
        self.reload.setObjectName("reload")
        self.gridLayout.addWidget(self.reload, 0, 4, 1, 1)
        self.addrsBar = QtGui.QLineEdit(self.centralWidget)
        self.addrsBar.setText("")
        self.addrsBar.setObjectName("addrsBar")
        self.gridLayout.addWidget(self.addrsBar, 0, 5, 1, 1)
        self.back = QtGui.QPushButton(self.centralWidget)
        self.back.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/back_ic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back.setIcon(icon4)
        self.back.setObjectName("back")
        self.gridLayout.addWidget(self.back, 0, 1, 1, 1)
        self.startReading = QtGui.QPushButton(self.centralWidget)
        self.startReading.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/read_ic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startReading.setIcon(icon5)
        self.startReading.setObjectName("startReading")
        self.gridLayout.addWidget(self.startReading, 0, 7, 1, 1)
        self.mic = QtGui.QPushButton(self.centralWidget)
        self.mic.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/mic_ic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mic.setIcon(icon6)
        self.mic.setObjectName("mic")
        self.gridLayout.addWidget(self.mic, 0, 6, 1, 1)
        SweetPea.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(SweetPea)
        self.statusBar.setObjectName("statusBar")
        SweetPea.setStatusBar(self.statusBar)
        self.actionNew_Tab = QtGui.QAction(SweetPea)
        self.actionNew_Tab.setObjectName("actionNew_Tab")
        self.actionClose_This_Tab = QtGui.QAction(SweetPea)
        self.actionClose_This_Tab.setObjectName("actionClose_This_Tab")
        self.actionClose_All = QtGui.QAction(SweetPea)
        self.actionClose_All.setObjectName("actionClose_All")
        self.actionHelp = QtGui.QAction(SweetPea)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtGui.QAction(SweetPea)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(SweetPea)
        QtCore.QMetaObject.connectSlotsByName(SweetPea)
        SweetPea.setTabOrder(self.back, self.forward)
        SweetPea.setTabOrder(self.forward, self.cancel)
        SweetPea.setTabOrder(self.cancel, self.reload)
        SweetPea.setTabOrder(self.reload, self.addrsBar)
        SweetPea.setTabOrder(self.addrsBar, self.webView)

    def retranslateUi(self, SweetPea):
        SweetPea.setWindowTitle(QtGui.QApplication.translate("SweetPea", "Sweetpea", None, QtGui.QApplication.UnicodeUTF8))
        self.forward.setToolTip(QtGui.QApplication.translate("SweetPea", "Go Forward", None, QtGui.QApplication.UnicodeUTF8))
        self.forward.setStatusTip(QtGui.QApplication.translate("SweetPea", "Forward Button  Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.forward.setShortcut(QtGui.QApplication.translate("SweetPea", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel.setToolTip(QtGui.QApplication.translate("SweetPea", "Cancel Page Loading", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel.setStatusTip(QtGui.QApplication.translate("SweetPea", "Cancel Button  Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel.setShortcut(QtGui.QApplication.translate("SweetPea", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.reload.setToolTip(QtGui.QApplication.translate("SweetPea", "Reload This Page", None, QtGui.QApplication.UnicodeUTF8))
        self.reload.setStatusTip(QtGui.QApplication.translate("SweetPea", "Reloading Button  Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.reload.setShortcut(QtGui.QApplication.translate("SweetPea", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.addrsBar.setToolTip(QtGui.QApplication.translate("SweetPea", "Enter Web Address here", None, QtGui.QApplication.UnicodeUTF8))
        self.addrsBar.setStatusTip(QtGui.QApplication.translate("SweetPea", "Address Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.addrsBar.setWhatsThis(QtGui.QApplication.translate("SweetPea", "Address Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.addrsBar.setPlaceholderText(QtGui.QApplication.translate("SweetPea", "Enter Web Address here and Hit enter", None, QtGui.QApplication.UnicodeUTF8))
        self.back.setToolTip(QtGui.QApplication.translate("SweetPea", "Go Backward", None, QtGui.QApplication.UnicodeUTF8))
        self.back.setStatusTip(QtGui.QApplication.translate("SweetPea", "Backward Button    Backspace", None, QtGui.QApplication.UnicodeUTF8))
        self.back.setShortcut(QtGui.QApplication.translate("SweetPea", "Backspace", None, QtGui.QApplication.UnicodeUTF8))
        self.startReading.setToolTip(QtGui.QApplication.translate("SweetPea", "Click for Start Reading the Page", None, QtGui.QApplication.UnicodeUTF8))
        self.startReading.setStatusTip(QtGui.QApplication.translate("SweetPea", "Reader Button  Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.startReading.setShortcut(QtGui.QApplication.translate("SweetPea", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.mic.setToolTip(QtGui.QApplication.translate("SweetPea", "Give Voice Command", None, QtGui.QApplication.UnicodeUTF8))
        self.mic.setStatusTip(QtGui.QApplication.translate("SweetPea", "Audio Command Listener  Ctrl+M", None, QtGui.QApplication.UnicodeUTF8))
        self.mic.setShortcut(QtGui.QApplication.translate("SweetPea", "Ctrl+M", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Tab.setText(QtGui.QApplication.translate("SweetPea", "New Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Tab.setShortcut(QtGui.QApplication.translate("SweetPea", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose_This_Tab.setText(QtGui.QApplication.translate("SweetPea", "Close This Tab", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose_All.setText(QtGui.QApplication.translate("SweetPea", "Close All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("SweetPea", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("SweetPea", "About", None, QtGui.QApplication.UnicodeUTF8))

from PySide import QtWebKit
